# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=256)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['file_name'],
            },
        ),
        migrations.CreateModel(
            name='VideoFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('full_name', models.CharField(max_length=128)),
                ('aliases', models.CharField(max_length=512)),
                ('priority', models.PositiveIntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_player.VideoFolder'),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set([('folder', 'file_name')]),
        ),
    ]
